export const fixtures = {
  admin: {
    id: "admin-1",
    username: "admin",
    password: "$2a$12$LJ3r8Jqx2yG7K5bQ1Z3mXeO6hY7qR9wKv8dXp3cN0fT4iU5gW6S2",
    name: "Test Admin",
    role: "admin",
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01"),
  },

  settings: {
    id: "default",
    businessName: "Test Business",
    businessDesc: "A test business for unit testing",
    welcomeMessage: "Hello! How can I help?",
    tone: "friendly",
    language: "auto",
    aiProvider: "gemini",
    aiModel: "gemini-2.5-flash",
    aiApiKey: "sk-test-key-12345",
    maxTokens: 1000,
    temperature: 0.7,
    smtpHost: "smtp.test.com",
    smtpPort: 587,
    smtpUser: "test@test.com",
    smtpPass: "smtp-password",
    smtpFrom: "support@test.com",
    imapHost: "imap.test.com",
    imapPort: 993,
    imapUser: "test@test.com",
    imapPass: "imap-password",
    twilioSid: "AC1234567890",
    twilioToken: "twilio-auth-token",
    twilioPhone: "+1234567890",
    elevenLabsKey: "el-key-12345",
    elevenLabsVoice: "voice-id-1",
    whatsappMode: "web",
    whatsappApiKey: "wa-key-12345",
    whatsappPhone: "+1234567890",
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01"),
  },

  conversation: {
    id: "conv-1",
    channel: "whatsapp",
    customerName: "John Doe",
    customerContact: "+1555000111",
    status: "active",
    satisfaction: null,
    summary: null,
    metadata: null,
    createdAt: new Date("2025-01-15"),
    updatedAt: new Date("2025-01-15"),
  },

  message: {
    id: "msg-1",
    conversationId: "conv-1",
    role: "customer",
    content: "I need help with my order",
    mediaType: null,
    mediaUrl: null,
    toolCalls: null,
    createdAt: new Date("2025-01-15"),
  },

  ticket: {
    id: "ticket-1",
    title: "Order not delivered",
    description: "Customer reports order #123 not delivered",
    priority: "high",
    status: "open",
    resolution: null,
    conversationId: "conv-1",
    departmentId: "dept-1",
    assignedToId: null,
    createdAt: new Date("2025-01-15"),
    updatedAt: new Date("2025-01-15"),
  },

  department: {
    id: "dept-1",
    name: "Technical Support",
    description: "Handles technical issues",
    email: "tech@test.com",
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01"),
  },

  teamMember: {
    id: "member-1",
    name: "Jane Smith",
    email: "jane@test.com",
    phone: "+1555000222",
    role: "agent",
    expertise: "billing,payments",
    departmentId: "dept-1",
    isAvailable: true,
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01"),
  },

  knowledgeCategory: {
    id: "cat-1",
    name: "General FAQ",
    description: "Frequently asked questions",
    icon: "help",
    color: "#3B82F6",
    sortOrder: 0,
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01"),
  },

  knowledgeEntry: {
    id: "entry-1",
    categoryId: "cat-1",
    title: "Return Policy",
    content: "Items can be returned within 30 days.",
    priority: 10,
    isActive: true,
    version: 1,
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01"),
  },

  customer: {
    id: "cust-1",
    name: "John Doe",
    email: "john@example.com",
    phone: "+1555000111",
    whatsapp: "+1555000111",
    tags: "vip",
    isBlocked: false,
    firstContact: new Date("2025-01-01"),
    lastContact: new Date("2025-01-15"),
    metadata: null,
    notes: null,
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-15"),
  },

  webhook: {
    id: "wh-1",
    name: "Slack Notifications",
    description: "Send ticket alerts to Slack",
    url: "https://hooks.slack.com/test",
    method: "POST",
    headers: { Authorization: "Bearer slack-token" },
    triggerOn: "ticket_created",
    isActive: true,
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01"),
  },

  automationRule: {
    id: "rule-1",
    name: "Route billing questions",
    description: "Auto-route billing inquiries to billing department",
    type: "auto_route",
    isActive: true,
    conditions: [{ field: "message_content", operator: "contains", value: "billing" }],
    actions: [{ type: "route", value: "billing" }],
    priority: 10,
    triggerCount: 0,
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01"),
  },

  cannedResponse: {
    id: "cr-1",
    title: "Greeting",
    content: "Hello! Thank you for reaching out. How can I assist you today?",
    category: "general",
    shortcut: "/greet",
    isActive: true,
    usageCount: 5,
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01"),
  },

  apiKeyRecord: {
    id: "key-1",
    name: "Integration Key",
    key: "salondesk_live_abc123def456",
    isActive: true,
    lastUsed: null,
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01"),
  },

  slaRule: {
    id: "sla-1",
    name: "High Priority SLA",
    description: "Response within 1 hour for high priority",
    channel: "all",
    priority: "high",
    firstResponseMins: 60,
    resolutionMins: 480,
    isActive: true,
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01"),
  },
} as const;
